import { Lightbulb, MessagesSquare, Compass, BookOpen, Sparkles, type LucideIcon } from "lucide-react";

/**
 * The "Second Brain" content model.
 * Each category is anchored to a 3D position on/near the brain surface so the
 * scene and the UI stay in sync. Items are AI-surfaced in production; here they
 * are seeded, realistic, and mutable from the capture bar.
 */
export type BrainCategoryId = "ideas" | "thoughts" | "next" | "knowledge" | "insights";

export interface BrainCategory {
  id: BrainCategoryId;
  label: string;
  icon: LucideIcon;
  color: string;          // hex, drives the 3D node + UI accents
  blurb: string;
  anchor: [number, number, number]; // world position of the 3D marker
  phase: number;          // pulse offset
}

export const categories: BrainCategory[] = [
  { id: "ideas", label: "Ideas", icon: Lightbulb, color: "#22d3ee", blurb: "Sparks worth keeping.", anchor: [1.05, 0.58, 0.42], phase: 0.0 },
  { id: "thoughts", label: "Thoughts", icon: MessagesSquare, color: "#38bdf8", blurb: "Reflections, captured.", anchor: [0.15, 1.05, 0.15], phase: 1.1 },
  { id: "next", label: "Next steps", icon: Compass, color: "#34d399", blurb: "What to do next.", anchor: [1.28, -0.08, -0.22], phase: 2.2 },
  { id: "knowledge", label: "Knowledge", icon: BookOpen, color: "#60a5fa", blurb: "Your second memory.", anchor: [-1.0, 0.52, -0.34], phase: 3.3 },
  { id: "insights", label: "Insights", icon: Sparkles, color: "#5eead4", blurb: "Connections the AI found.", anchor: [0.1, 0.18, 1.18], phase: 4.4 },
];

export type BrainItemKind = "idea" | "thought" | "task" | "note" | "insight";

export interface BrainItem {
  id: string;
  category: BrainCategoryId;
  kind: BrainItemKind;
  /** Present on user-captured items; seeded items resolve text from i18n. */
  title?: string;
  detail?: string;
  done?: boolean;
  ts?: string;
  ai?: boolean;           // surfaced/generated by the AI
}

/**
 * Seed items carry structure only — their text lives in the i18n dictionaries
 * (`brain.items[id]`) so the whole module reads natively in EN and FR.
 */
export const seedItems: BrainItem[] = [
  { id: "i1", category: "ideas", kind: "idea", ts: "2d" },
  { id: "i2", category: "ideas", kind: "idea", ts: "4d", ai: true },
  { id: "i3", category: "ideas", kind: "idea", ts: "1w" },

  { id: "t1", category: "thoughts", kind: "thought", ts: "1d" },
  { id: "t2", category: "thoughts", kind: "thought", ts: "3d" },

  { id: "n1", category: "next", kind: "task", ai: true },
  { id: "n2", category: "next", kind: "task", ai: true },
  { id: "n3", category: "next", kind: "task", ai: true, done: true },

  { id: "k1", category: "knowledge", kind: "note", ts: "1w" },
  { id: "k2", category: "knowledge", kind: "note", ts: "2w" },

  { id: "s1", category: "insights", kind: "insight", ai: true },
  { id: "s2", category: "insights", kind: "insight", ai: true },
];

export const categoryById = (id: BrainCategoryId) => categories.find((c) => c.id === id)!;
